---

- hosts: postgresql
  roles:
    - role: postgresql
      vars:
        postgresql_dbname: "{{ boundary_psql_dbname }}"
        postgresql_user: "{{ boundary_psql_username }}"
        postgresql_password: "{{ boundary_psql_password }}"
  become: true

- hosts: boundary_controllers,boundary_workers
  roles:
    - role: boundary
      tags: boundary
  become: true
  tasks:
    - name: Add hosts setting
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "^{{ boundary_address }}\\s+{{ inventory_hostname }}\\s$"
        line: "{{ boundary_address }} {{ inventory_hostname }}"
        owner: root
        group: root
        mode: '0644'

    - name: Show default username and password if necessary
      debug:
        msg: "{{ boundary_database_init.stdout_lines }}"
      when: boundary_database_init is defined and boundary_database_init.changed
